local TowerShop = {
	["Cowboy"] = {
		["Name"] = "Cowboy",
		["ImageAsset"] = "rbxassetid://122800238183729",
		["Price"] = 100,
	},
	["Mafia"] = {
		["Name"] = "Mafia",
		["ImageAsset"] = "rbxassetid://92480627340201",
		["Price"] = 1000,
	},
	["Miku"] = {
		["Name"] = "Miku",
		["ImageAsset"] = "rbxassetid://84561111423443",
		["Price"] = 100000,
	},
	["Grenadier"] = {
		["Name"] = "Grenadier",
		["ImageAsset"] = "rbxassetid://131329681805299",
		["Price"] = 300,
	},
	["Gunner"] = {
		["Name"] = "Gunner",
		["ImageAsset"] = "rbxassetid://84165230579797",
		["Price"] = 200,
	},
	["Samurai"] = {
		["Name"] = "Samurai",
		["ImageAsset"] = "rbxassetid://81916836515608",
		["Price"] = 500,
	},
}

return TowerShop
